apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  alert.rules: |
    groups:
    - name: nba-stats-alerts
      rules:
      # API Performance Alerts
      - alert: HighErrorRate
        expr: rate(api_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 10% for 5 minutes

      - alert: SlowAPIResponse
        expr: rate(api_request_duration_seconds_bucket{le="1.0"}[5m]) < 0.95
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow API response times
          description: More than 5% of requests are taking longer than 1 second

      # Database Performance Alerts
      - alert: SlowDatabaseQueries
        expr: rate(db_query_duration_seconds_bucket{le="0.5"}[5m]) < 0.95
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow database queries detected
          description: More than 5% of database queries are taking longer than 500ms

      # Data Freshness Alerts
      - alert: DataFreshnessWarning
        expr: data_freshness_hours > 24
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: Data is becoming stale
          description: Data has not been updated in over 24 hours

      # Scheduler Job Alerts
      - alert: SchedulerJobFailure
        expr: scheduler_job_count{status="failure"} > 0
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: Scheduler job failure detected
          description: One or more scheduler jobs have failed

      # Resource Usage Alerts
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container!=""} / container_spec_memory_limit_bytes{container!=""} * 100 > 90
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Container memory usage is above 90%

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{container!=""}[5m]) * 100 > 90
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: Container CPU usage is above 90%

      # WebSocket Connection Alerts
      - alert: HighWebSocketConnections
        expr: websocket_connections > 900
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High WebSocket connection count
          description: WebSocket connections are approaching the limit (1000)

      # External API Health Alerts
      - alert: ExternalAPIErrors
        expr: rate(external_api_calls_total{status="error"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: External API errors detected
          description: Error rate for external API calls is above 10% 