apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-test
  labels:
    app: memory-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-test
  template:
    metadata:
      labels:
        app: memory-test
    spec:
      containers:
      - name: memory-test
        image: polinux/stress
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            stress --vm 1 --vm-bytes $(shuf -i 50-100 -n 1)M --vm-hang 0 --timeout $(shuf -i 10-30 -n 1)s
            sleep $(shuf -i 5-15 -n 1)
          done
---
apiVersion: v1
kind: Service
metadata:
  name: memory-test-service
spec:
  selector:
    app: memory-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 