apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-backend
  labels:
    app: nba-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nba-backend
  template:
    metadata:
      labels:
        app: nba-backend
    spec:
      containers:
      - name: nba-backend
        image: ghcr.io/markybuilds/nba-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: nba-app-secrets
              key: supabase-url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: nba-app-secrets
              key: supabase-key
        - name: NBA_API_KEY
          valueFrom:
            secretKeyRef:
              name: nba-app-secrets
              key: nba-api-key
        - name: NBA_RATE_LIMIT_SECONDS
          value: "1"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nba-backend-service
spec:
  selector:
    app: nba-backend
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP