version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NBA_API_KEY=${NBA_API_KEY}
      - NBA_RATE_LIMIT_SECONDS=1
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Frontend Next.js service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend 