apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-stats-frontend
  namespace: ${NAMESPACE}
  labels:
    app: nba-stats-frontend
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nba-stats-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nba-stats-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ${IMAGE_REGISTRY}/nba-stats-frontend:${FRONTEND_VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_url
        - name: NEXT_PUBLIC_APP_ENV
          value: "production"
        - name: NEXT_PUBLIC_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: app_version
        volumeMounts:
        - name: frontend-config-volume
          mountPath: /app/public/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: frontend-config-volume
        configMap:
          name: frontend-config
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: nba-stats-frontend
  namespace: ${NAMESPACE}
  labels:
    app: nba-stats-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nba-stats-frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nba-stats-frontend
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nba-stats-frontend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 